import {useState} from 'react'
import { Section, Wrapper, H1, Paragraph, FormContainer, LoaderContainer, LoaderWrapper } from './styles'
import { Loader, Card, FormField } from '../../components'

const Home = () => {
  const [loading, setLoading] = useState(true);
  const [allPosts, setAllPosts] = useState(null)

  return (
    <Section>
      <Wrapper>
        <H1>The Community Showcase</H1>
        <Paragraph>Browse through a collection of imaginative images generated by AI</Paragraph>
      </Wrapper>

      <FormContainer>
        <FormField />
      </FormContainer>

      <LoaderContainer>
        {loading ? (
         <LoaderWrapper>
            <Loader/>
          </LoaderWrapper>
        ) : (
          <></>
        )}
      </LoaderContainer>

    </Section>
  )
}

export default Home