import React, { useState } from 'react'
import { useNavigate } from 'react-router-dom'

import { preview } from '../../assets'
import { getRandomPrompt } from '../../utils'
import { FormField, Loader } from '../../components'
import { Form, FormContainer, H1, Paragraph, Section, Wrapper } from './styles'

const CreatePost = () => {
  const navigate = useNavigate();
  const [generatingImg, setGeneratingImg] = useState(false)
  const [loading, setLoading] = useState(false)
  const [form, setForm] = useState({
    name: '',
    prompt: '',
    photo: ''
  });

  const handleSubmit = () => {

  }
  const handleChange = (e) => {

  }
  const handleSurpriseMe = () => {

  }

  return (
    <Section>
      <Wrapper>
        <H1>Create</H1>
        <Paragraph>Create images generated by AI and share them with the community</Paragraph>
      </Wrapper>

      <Form onSubmit={handleSubmit}>
        <FormContainer>
          <FormField
            labelName="Your name"
            type="text"
            name="name"
            placeholder="John Doe"
            value={form.name}
            handleChange={handleChange}
          />
          <FormField
            labelName="Your Prompt"
            type="text"
            name="prompt"
            placeholder="A man wanders through the rainy streets of Tokyo, with bright neon signs, 50mm"
            value={form.prompt}
            handleChange={handleChange}
            isSurpriseMe
            handleSurpriseMe={handleSurpriseMe}
          />
        </FormContainer>
      </Form>
    </Section>
  )
}

export default CreatePost